import Link from 'next/link';
import Head from 'next/head';

export default function DocsPage () {
  return <>
    <Head>
      <title>Docs Root ✔</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div>
      <h1>Docs Page a</h1>
      <Link className="base-navlink" href={{pathname: '/docs/User'}} >User</Link>
      <Link className="base-navlink" href={{pathname: '/docs/Console'}} >Console</Link>
      <Link className="base-navlink" href={{pathname: '/docs/Agent'}} >Agent</Link>
      <Link className="base-navlink" href={{pathname: '/docs/Scratch'}} >Scratch</Link>
    </div>
    <div>

    </div>
  </>
}