import Head from 'next/head';
import { MainLayout } from '@layout';
import { useEffect } from 'react';
import { debounce } from '@common/helper';

export default function Home() {
  useEffect(() => {
    window.addEventListener(
      'resize',
      debounce(() => {
        console.log('chua debounce');
      })
    );
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MainLayout>
          <div>hello</div>
        </MainLayout>
      </main>
    </>
  );
}
